[package]
name = "base"
version = "0.10.4"
description = "The Motoko base library"
repository = "https://github.com/dfinity/motoko-base"
keywords = [ "base" ]
license = "Apache-2.0"

[dev-dependencies]
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0"

[toolchain]
moc = "0.10.4"
wasmtime = "17.0.0"